### ISSUE TITLE
bundle exec rack db:setup error

### ISSUE THREAD

**Issue by preethi-ravichandran** [toddwschneider/nba-shots-db#1]
while executing the bundle command, getting error like:
bash: /usr/bin/bundle: /usr/bin/ruby: bad interpreter: No such file or directory
Getting the same error for all the three bundle commands.

**Comment by toddwschneider** [comment]
For one thing, the command is `rake`, not `rack`, though I'm guessing that's a typo in the issue title since the error would be different otherwise

It looks like maybe a problem with your Ruby setup. I'd recommend following the Rails getting started guide and making sure you can create/start a toy Rails app: http://guides.rubyonrails.org/getting_started.html

You could also try Stack Overflow, this question looks like it might be helpful: https://stackoverflow.com/questions/32849303/rbenv-and-bundler-bad-interpreter-no-such-file-or-directory

**Comment by Preravana** [comment]
I am getting error like this:

FATAL:  role "preethi" does not exist
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"nba-shots-db_development"}
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "preethi" does not exist
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:701:in `rescue in connect'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:697:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:221:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:88:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:10:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:117:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
PG::ConnectionBad: FATAL:  role "preethi" does not exist
/var/lib/gems/2.3.0/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
/var/lib/gems/2.3.0/gems/pg-1.0.0/lib/pg.rb:56:in `new'
/var/lib/gems/2.3.0/gems/pg-1.0.0/lib/pg.rb:56:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:697:in `connect'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:221:in `initialize'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/connection_handling.rb:88:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:10:in `connection'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/postgresql_database_tasks.rb:19:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:117:in `create'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:137:in `block in create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:305:in `block in each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:302:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/tasks/database_tasks.rb:136:in `create_current'
/var/lib/gems/2.3.0/gems/activerecord-5.1.5/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create
(See full trace by running task with --trace)

**Comment by preethi-ravichandran** [comment]
yes, I have done the steps mentioned. **But "bundle exec rake import_all_shots" doesn't run anything.** But "bundle exec rake jobs:work" runs.

**Comment by toddwschneider** [comment]
`bundle exec rake import_all_shots` creates 2 jobs in the `delayed_jobs` table. Nothing else visible happens until you run `bundle exec rake jobs:work`, which will begin to populate the `shots` table

Can you check if there are any records in your `players` table?

**Comment by preethi-ravichandran** [comment]
yes I have checked but I can't find nothing. Also, it ran for around 10
hours, but it didn't stop running.

**Comment by toddwschneider** [comment]
@Preravana if the `players` table is empty then `bundle exec rake db:setup` did not work because that command is supposed to populate the `players` table. I wonder if the NBA Stats API is available wherever you're located. Also note that the NBA Stats API does not work from AWS and other cloud services.

Do you see anything if you visit this URL in your browser?: http://stats.nba.com/stats/commonallplayers?LeagueId=00&Season=2017-18&IsOnlyCurrentSeason=0
